server:
  port: 81

spring:
  servlet:
    multipart:
      max-file-size: 10MB         # 单个文件的最大值
      max-request-size: 10MB      # 上传文件总的最大值
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alumni_system?serverTimezone=Asia/Shanghai
    username: root
    password: bt2642232
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

